### ISSUE TITLE
pd dev starts a new simulator window

### ISSUE THREAD

**Issue by DomDomHaas** [colingourlay/create-playdate#2]
When having the `npm run start` aka. pd dev running, after every save of a file the build is deployed which is great.
Hotreload for the win!

But it opens an new window after every save... is there something I can change to avoid that?

**Comment by colingourlay** [comment]
Hey @DomDomHaas. What platform are you running this on? I think I ran into this exact issue when developing this tool (the hot-reload process wasn't closing the existing Simulator before launching it again). Hopefully we can defeat this bug for good!

**Comment by DomDomHaas** [comment]
Windows, do you need specific details?

**Comment by colingourlay** [comment]
I think I've cracked this. I had some funky logic in how the watcher tries to kill existing build/simulator processes and launch new ones. Try updating your `pddx` package and let me know how you go:

```sh
npm install -D pddx@latest
```
